# Generated by Django 5.1.6 on 2025-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattlemetricsSetPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('hmac_secret_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Battlemetrics подключение обновления времени',
                'verbose_name_plural': 'Battlemetrics подключения обновлений времени',
            },
        ),
        migrations.CreateModel(
            name='PlaytimeGetPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('hmac_secret_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Подключение для обновления времени',
                'verbose_name_plural': 'Подключения для обновлений времени',
            },
        ),
        migrations.CreateModel(
            name='Playtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=18, verbose_name='Steam ID 64')),
                ('game_id', models.IntegerField(verbose_name='Game ID')),
                ('steam_playtime', models.FloatField(null=True, verbose_name='Игровое время по Steam')),
                ('bm_playtime', models.FloatField(null=True, verbose_name='Игровое время по Battlemetrics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Игровое время',
                'verbose_name_plural': 'Игровое время игроков',
                'unique_together': {('steam_id', 'game_id')},
            },
        ),
    ]
