# Generated by Django 5.1.6 on 2025-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlemetricssetpath',
            options={'verbose_name': 'Подключение Battlemetrics', 'verbose_name_plural': '2. Подключения Battlemetrics'},
        ),
        migrations.AlterModelOptions(
            name='playtime',
            options={'verbose_name': 'Игровое время', 'verbose_name_plural': '1. Игровое время игроков'},
        ),
        migrations.AlterModelOptions(
            name='playtimegetpath',
            options={'verbose_name': 'Подключение скриптов', 'verbose_name_plural': '3. Подключения скриптов'},
        ),
        migrations.AlterField(
            model_name='playtime',
            name='bm_playtime',
            field=models.IntegerField(null=True, verbose_name='Игровое время по Battlemetrics'),
        ),
        migrations.AlterField(
            model_name='playtime',
            name='steam_playtime',
            field=models.IntegerField(null=True, verbose_name='Игровое время по Steam'),
        ),
    ]
