# Generated by Django 5.1.6 on 2025-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playtime", "0002_alter_battlemetricssetpath_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="battlemetricssetpath",
            options={
                "verbose_name": "'Подключение Battlemetrics'",
                "verbose_name_plural": "2. Подключения Battlemetrics",
            },
        ),
        migrations.AlterModelOptions(
            name="playtime",
            options={"verbose_name": "'Игровое время'", "verbose_name_plural": "1. Игровое время игроков"},
        ),
        migrations.AlterModelOptions(
            name="playtimegetpath",
            options={"verbose_name": "'Подключение скриптов'", "verbose_name_plural": "3. Подключения скриптов"},
        ),
        migrations.AddField(
            model_name="battlemetricssetpath",
            name="fixed_game_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Зафиксированный Game ID"),
        ),
        migrations.AddField(
            model_name="playtimegetpath",
            name="fixed_game_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Зафиксированный Game ID"),
        ),
        migrations.AlterField(
            model_name="battlemetricssetpath",
            name="enabled",
            field=models.BooleanField(default=False, verbose_name="Включен"),
        ),
        migrations.AlterField(
            model_name="battlemetricssetpath",
            name="hmac_secret_key",
            field=models.CharField(max_length=255, verbose_name="HMAC ключ"),
        ),
        migrations.AlterField(
            model_name="battlemetricssetpath",
            name="path",
            field=models.CharField(max_length=255, unique=True, verbose_name="Путь"),
        ),
        migrations.AlterField(
            model_name="playtime",
            name="bm_playtime",
            field=models.IntegerField(blank=True, null=True, verbose_name="Игровое время по Battlemetrics"),
        ),
        migrations.AlterField(
            model_name="playtime",
            name="steam_playtime",
            field=models.IntegerField(blank=True, null=True, verbose_name="Игровое время по Steam"),
        ),
        migrations.AlterField(
            model_name="playtimegetpath",
            name="enabled",
            field=models.BooleanField(default=False, verbose_name="Включен"),
        ),
        migrations.AlterField(
            model_name="playtimegetpath",
            name="hmac_secret_key",
            field=models.CharField(max_length=255, verbose_name="HMAC ключ"),
        ),
        migrations.AlterField(
            model_name="playtimegetpath",
            name="path",
            field=models.CharField(max_length=255, unique=True, verbose_name="Путь"),
        ),
    ]
